"use strict";
require("electron");
require("node:url");
require("node:fs");
require("node:path");
require("node:fs/promises");
require("node:child_process");
require("./main-Bt8d1A99.cjs");
require("node:util");
require("node:crypto");
